import requests
import json
import base64
import os

API_KEY = "AIzaSyCBTkPLp6NymIv1-FC60_PteLe_m_B7jME"
URL = f"https://texttospeech.googleapis.com/v1/text:synthesize?key={API_KEY}"
OUTPUT_FILE = "test_audio.mp3"

data = {
    "input": {
        "text": "This is a test audio generated by Bitlance Automation using Google Cloud Text to Speech."
    },
    "voice": {
        "languageCode": "en-US",
        "name": "en-US-Journey-F", # A nice neural voice
        "ssmlGender": "FEMALE"
    },
    "audioConfig": {
        "audioEncoding": "MP3"
    }
}

try:
    print(f"Generating audio...")
    response = requests.post(URL, headers={"Content-Type": "application/json"}, data=json.dumps(data))
    
    if response.status_code == 200:
        result = response.json()
        if "audioContent" in result:
            audio_bytes = base64.b64decode(result["audioContent"])
            with open(OUTPUT_FILE, "wb") as f:
                f.write(audio_bytes)
            print(f"✅ Audio generated successfully!")
            print(f"📁 Saved to: {os.path.abspath(OUTPUT_FILE)}")
        else:
            print("⚠️ Request succeeded but no audio content found.")
    else:
        print(f"❌ API Request Failed. Status Code: {response.status_code}")
        print("Response:", response.text)

except Exception as e:
    print("❌ Script Error:", str(e))