/**
 * articleController.js
 * Saves blog posts generated by the Python AI service.
 * Handles: Supabase save, image upload, credit deduction, push notification.
 */

import { createClient } from '@supabase/supabase-js';
import axios from 'axios';
import CreditLedgerService from '../services/creditLedgerService.js';
import { sendPushNotification } from '../services/onesignalService.js';
import { supabaseAdmin } from '../config/supabaseClient.js';
import { decryptData } from '../utils/encryption.js';

const ADMIN_ID = '0d396440-7d07-407c-89da-9cb93e353347';
const PYTHON_API_URL = process.env.PYTHON_API_URL || 'http://localhost:8000';

// Determine table: admins default to company_articles unless explicitly overridden
const getTableName = (userId, targetTable) => {
    if (userId === ADMIN_ID) {
        return targetTable === 'articles' ? 'articles' : 'company_articles';
    }
    return 'articles';
};

// Slug generator
const generateSlug = (text) =>
    text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

// Upload article to user's WordPress site (returns { link, postId } or null)
const uploadToWordPress = async (wpUrl, wpUser, wpPassword, title, content, imageUrl) => {
    try {
        const base = wpUrl.replace(/\/+$/, '');
        const authHeader = 'Basic ' + Buffer.from(`${wpUser}:${wpPassword}`).toString('base64');

        // 1. Upload featured image to WP media library
        let featuredMediaId = null;
        if (imageUrl) {
            try {
                const imgRes = await axios.get(imageUrl, { responseType: 'arraybuffer', timeout: 15000 });
                const imgBuffer = Buffer.from(imgRes.data);
                const contentType = (imgRes.headers['content-type'] || 'image/png').split(';')[0];
                const ext = contentType.split('/')[1] || 'png';
                const filename = `blog-${Date.now()}.${ext}`;

                // Use native FormData (Node 18+)
                const mediaRes = await fetch(`${base}/wp-json/wp/v2/media`, {
                    method: 'POST',
                    headers: {
                        Authorization: authHeader,
                        'Content-Type': contentType,
                        'Content-Disposition': `attachment; filename="${filename}"`,
                    },
                    body: Buffer.from(imgBuffer),
                    signal: AbortSignal.timeout(30000),
                });
                if (mediaRes.ok) {
                    const mediaData = await mediaRes.json();
                    featuredMediaId = mediaData.id || null;
                } else {
                    console.warn('[WP Upload] Image upload returned:', mediaRes.status);
                }
            } catch (imgErr) {
                console.warn('[WP Upload] Image upload failed (continuing without):', imgErr.message);
            }
        }

        // 2. Create post as draft
        const postPayload = {
            title,
            content,
            status: 'draft',
            excerpt: content.substring(0, 200).replace(/<[^>]*>/g, ''),
            ...(featuredMediaId && { featured_media: featuredMediaId }),
        };

        const postRes = await fetch(`${base}/wp-json/wp/v2/posts`, {
            method: 'POST',
            headers: { Authorization: authHeader, 'Content-Type': 'application/json' },
            body: JSON.stringify(postPayload),
            signal: AbortSignal.timeout(30000),
        });

        if (!postRes.ok) {
            const errText = await postRes.text();
            throw new Error(`WP API ${postRes.status}: ${errText.substring(0, 200)}`);
        }

        const postData = await postRes.json();
        return { link: postData.link, postId: postData.id };
    } catch (err) {
        console.error('[WP Upload] Failed:', err.message);
        return null;
    }
};

// Upload image URL (or base64 data URI) to Supabase Storage and return public URL
const uploadImageToSupabase = async (imageUrl) => {
    if (!imageUrl) return null;
    try {
        let buffer;
        let contentType = 'image/png';

        if (imageUrl.startsWith('data:')) {
            // Handle base64 data URI from Gemini Imagen (e.g. data:image/png;base64,...)
            const [meta, b64data] = imageUrl.split(',');
            const mimeMatch = meta.match(/data:([^;]+);base64/);
            if (mimeMatch) contentType = mimeMatch[1];
            buffer = Buffer.from(b64data, 'base64');
        } else {
            // Handle regular http(s) URLs (e.g. DALL-E, or any CDN URL)
            const response = await axios.get(imageUrl, { responseType: 'arraybuffer', timeout: 15000 });
            buffer = Buffer.from(response.data);
            const ct = response.headers['content-type'];
            if (ct) contentType = ct.split(';')[0];
        }

        const ext = contentType.split('/')[1] || 'png';
        const filename = `blog-${Date.now()}.${ext}`;
        const { data, error } = await supabaseAdmin.storage
            .from('blog-images')
            .upload(filename, buffer, { contentType, upsert: true });
        if (error) throw error;
        const { data: urlData } = supabaseAdmin.storage.from('blog-images').getPublicUrl(filename);
        return urlData.publicUrl;
    } catch (e) {
        console.error('Image upload failed:', e.message);
        return imageUrl.startsWith('data:') ? null : imageUrl; // don't return raw base64 as fallback
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/articles/generate
// Calls Python to generate, then saves result to Supabase
// ─────────────────────────────────────────────────────────────────────────────
// ─────────────────────────────────────────────────────────────────────────────
// Internal Helper: Generate and Save Article
// ─────────────────────────────────────────────────────────────────────────────
export const generateAndSaveArticleInternal = async ({
    userId, token, topic, industry, keywords, language, style, length, audience,
    image_option, custom_image_url, wp_url, wp_api_url, interlinks, author_name, author_bio, author_profile_id,
    author_details, category = 'Technology', tags = [], is_published = false,
    custom_slug, target_table
}) => {
    const tableName = getTableName(userId, target_table);

    // ── 1. Call Python generation service ─────────────────────────────────────
    if (!industry && !keywords) {
        console.log(`[AutoResearch] No industry/keywords provided for topic "${topic}" — AI will auto-research industry, keywords, and content strategy.`);
    }
    let genData;
    try {
        const genRes = await axios.post(
            `${PYTHON_API_URL}/api/blog/generate`,
            {
                topic, industry, keywords, language, style, length, audience, image_option, custom_image_url, wp_url, wp_api_url, interlinks
            },
            { headers: { Authorization: `Bearer ${token}` }, timeout: 300000 }
        );
        genData = genRes.data;
        if (!genData.success) throw new Error(genData.error || 'Generation failed');
    } catch (e) {
        console.error(`Python generation error for topic "${topic}":`, e.message);
        throw new Error(`Generation failed: ${e.message}`);
    }

    const { article: blogHtml, markdown: blogText, seoTitle, imageUrl: rawImageUrl, wordCount, plagiarismCheck, topic: finalTopic, keywords: finalKeywords } = genData;

    // ── 2. Upload image to Supabase Storage ───────────────────────────────────
    const imageUrl = await uploadImageToSupabase(rawImageUrl);

    // ── 3. Build slug ─────────────────────────────────────────────────────────
    const slug = custom_slug
        ? generateSlug(custom_slug)
        : `${generateSlug(seoTitle || finalTopic)}-${Math.floor(Math.random() * 1000)}`;

    const readTime = Math.ceil(wordCount / 200);

    // ── 4. Save to Supabase ───────────────────────────────────────────────────
    const scoped = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, {
        global: { headers: { Authorization: `Bearer ${token}` } },
        auth: { persistSession: false },
    });

    const payload = {
        user_id: userId,
        topic: finalTopic,
        keywords: finalKeywords,
        content: blogHtml,
        seo_title: seoTitle,
        seo_description: genData.seoDescription || `Read about ${finalTopic}. ${wordCount} words.`,
        image_url: imageUrl,
        featured_image: imageUrl,
        word_count: wordCount,
        plagiarism_check: plagiarismCheck,
        language: language || 'English',
        style: style || 'Professional',
        slug,
        category,
        tags,
        author_name: author_name || 'AI Agent',
        author_bio: author_bio || 'Generated by AI',
        author_profile_id: author_profile_id || null,
        author_details: author_details || null,
        is_published,
        publish_date: is_published ? new Date().toISOString() : null,
        estimated_read_time: readTime,
        social_share_enabled: true,
        comments_enabled: true,
    };

    const { data: savedArticle, error: saveError } = await (tableName === 'company_articles' ? supabaseAdmin : scoped)
        .from(tableName)
        .insert(payload)
        .select()
        .single();

    if (saveError) {
        console.error('Supabase save error:', saveError);
        throw new Error('Failed to save article');
    }

    // ── 5. Deduct credits ─────────────────────────────────────────────────────
    let ledgerResult = {};
    if (userId !== ADMIN_ID) {
        try {
            ledgerResult = await CreditLedgerService.deductCreditsWithLedger({
                userId,
                agentType: 'blog',
                referenceId: savedArticle.id,
                referenceTable: 'articles', // Force to 'articles' to satisfy DB constraint
                usageQuantity: 1,
                metadata: { topic: finalTopic, language, style, model: 'sonar-pro', category, actual_word_count: wordCount, actual_table: tableName },
            });
        } catch (e) {
            console.error('⚠️ Credit deduction failed (article saved):', e);
        }
    }

    // ── 6. Push notification — only for admin-published articles ─────────────
    if (userId === ADMIN_ID && is_published) {
        const articleUrl = `${process.env.APP_URL || 'https://www.bitlancetechhub.com'}/blogs/${slug}`;
        sendPushNotification(
            `New Article: ${finalTopic}`,
            `Check out our latest post on "${finalTopic}"!`,
            articleUrl,
            imageUrl
        ).catch(e => console.error('OneSignal Push fail:', e));
    }

    // ── 7. WordPress Auto-Upload Disabled ─────────────────────────────────────
    // User requested to NOT automatically post to WordPress upon generation. 
    // They will manually upload using the "Upload to WordPress" button instead.
    let wpPostLink = null;

    return {
        success: true,
        article: blogHtml,
        seoTitle,
        imageUrl,
        wordCount,
        plagiarismCheck,
        id: savedArticle.id,
        slug: savedArticle.slug,
        topic: finalTopic,
        creditsUsed: ledgerResult?.credits_deducted || 0,
        newBalance: ledgerResult?.new_balance || null,
        wpPostLink,
    };
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/articles/generate
// Calls Python to generate, then saves result to Supabase
// ─────────────────────────────────────────────────────────────────────────────
export const generateArticle = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;

    // ── 1. Credit pre-flight ──────────────────────────────────────────────────
    if (userId !== ADMIN_ID) {
        try {
            const check = await CreditLedgerService.validateCredits(userId, 'blog', 1);
            if (!check.hasEnough) {
                return res.status(402).json({
                    success: false,
                    error: 'Insufficient credits',
                    required: check.creditsNeeded,
                    balance: check.currentBalance,
                });
            }
        } catch (e) {
            console.error('Credit check failed:', e);
        }
    }

    // ── 2. Pre-build interlinks for admin from published articles ─────────────
    let interlinks = req.body.interlinks || null;
    if (!interlinks && userId === ADMIN_ID) {
        try {
            const { data: articles } = await supabaseAdmin
                .from('company_articles')
                .select('seo_title, slug')
                .eq('is_published', true)
                .order('created_at', { ascending: false })
                .limit(10);
            if (articles && articles.length > 0) {
                interlinks = articles.map(a => ({
                    title: a.seo_title || a.slug,
                    link: `https://www.bitlancetechhub.com/blogs/${a.slug}`
                }));
                console.log(`[Article] Pre-built ${interlinks.length} interlinks for admin`);
            }
        } catch (e) {
            console.warn('[Article] Failed to pre-build interlinks:', e.message);
        }
    }

    try {
        const result = await generateAndSaveArticleInternal({
            userId,
            token,
            ...req.body,
            interlinks,
            is_published: true  // Auto-publish immediately after generation
        });
        return res.json(result);
    } catch (error) {
        return res.status(500).json({ success: false, error: error.message });
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/articles/bulk-generate
// Bulk generate articles from uploaded Excel file
// ─────────────────────────────────────────────────────────────────────────────
import * as xlsx from 'xlsx';

export const bulkGenerateArticles = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;

    if (!req.file) {
        return res.status(400).json({ success: false, error: 'No Excel file uploaded' });
    }

    try {
        // Parse the Excel file
        const workbook = xlsx.read(req.file.buffer, { type: 'buffer' });
        const sheetName = workbook.SheetNames[0];
        const worksheet = workbook.Sheets[sheetName];
        let rows = xlsx.utils.sheet_to_json(worksheet, { defval: '' });

        // Support both new column names (Niche / Industry, Title / Topic) and old names (Industry, Topic)
        const getField = (row, newKey, oldKey) => (row[newKey] || row[oldKey] || '').toString().trim();

        // Filter out empty rows — accept either 'Title / Topic' or 'Topic'
        rows = rows.filter(row => (row['Title / Topic'] || row['Topic'] || '').toString().trim() !== '');

        if (rows.length === 0) {
            return res.status(400).json({ success: false, error: "Excel file is empty or missing 'Title / Topic' column. Download the template for the correct format." });
        }

        // Credit check for bulk if not admin
        if (userId !== ADMIN_ID) {
            const check = await CreditLedgerService.validateCredits(userId, 'blog', rows.length);
            if (!check.hasEnough) {
                return res.status(402).json({
                    success: false,
                    error: 'Insufficient credits for bulk generation',
                    required: check.creditsNeeded,
                    balance: check.currentBalance,
                });
            }
        }

        // Respond immediately to prevent timeout
        res.status(202).json({
            success: true,
            message: `Bulk processing started for ${rows.length} topics. This will take some time.`,
            count: rows.length
        });

        // Process in background
        (async () => {
            console.log(`Starting bulk generation for ${rows.length} articles...`);
            for (let i = 0; i < rows.length; i++) {
                const row = rows[i];
                const topicLabel = getField(row, 'Title / Topic', 'Topic');
                console.log(`[Bulk Gen ${i + 1}/${rows.length}] Processing topic: "${topicLabel}"`);
                try {
                    await generateAndSaveArticleInternal({
                        userId,
                        token,
                        topic: getField(row, 'Title / Topic', 'Topic'),
                        industry: getField(row, 'Niche / Industry', 'Industry'),
                        keywords: getField(row, 'Keywords', 'Keywords'),
                        category: row.Category || 'Technology',
                        target_table: row.TargetTable || 'company_articles',
                        language: row.Language || 'English',
                        style: row.Style || 'Professional',
                        length: row.Length || 'Medium',
                        audience: row.Audience || 'General',
                        is_published: true,
                    });
                    console.log(`[Bulk Gen ${i + 1}/${rows.length}] Success: "${topicLabel}"`);
                } catch (error) {
                    console.error(`[Bulk Gen ${i + 1}/${rows.length}] Failed for "${topicLabel}":`, error.message);
                }

                // Small delay between requests to avoid overloading Python API
                if (i < rows.length - 1) {
                    await new Promise(resolve => setTimeout(resolve, 5000));
                }
            }
            console.log('Bulk article generation completed.');
        })();

    } catch (error) {
        console.error('Bulk generation error:', error);
        // Only sensible to reply with error if we haven't already replied 202
        if (!res.headersSent) {
            return res.status(500).json({ success: false, error: 'Failed to process Excel file: ' + error.message });
        }
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// POST /api/blog/posts  — create article directly (not via AI generation)
// ─────────────────────────────────────────────────────────────────────────────
export const createArticle = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;
    const { target_table, is_company_blog, notification_settings, title, ...articleData } = req.body;
    const tableName = getTableName(userId, target_table);

    // Add user_id if not present
    articleData.user_id = articleData.user_id || userId;

    // Map frontend 'title' to database 'topic'
    if (title) articleData.topic = title;

    // Generate slug if missing
    if (!articleData.slug && (articleData.seo_title || articleData.topic)) {
        articleData.slug = `${generateSlug(articleData.seo_title || articleData.topic)}-${Math.floor(Math.random() * 1000)}`;
    }

    const sb = tableName === 'company_articles' ? supabaseAdmin :
        createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false } });

    const { data, error } = await sb.from(tableName).insert(articleData).select().single();
    if (error) {
        console.error('Create article error:', error);
        return res.status(500).json({ success: false, error: error.message });
    }

    res.json({ success: true, post: data });
};

// ─────────────────────────────────────────────────────────────────────────────
// CRUD — /api/blog/posts/:id  (list, get, update, delete)
// ─────────────────────────────────────────────────────────────────────────────

export const listArticles = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;
    const { page = 1, limit = 10, target_table } = req.query;
    const tableName = getTableName(userId, target_table);
    const offset = (parseInt(page) - 1) * parseInt(limit);

    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, {
        global: { headers: { Authorization: `Bearer ${token}` } },
        auth: { persistSession: false },
    });

    const { data, error, count } = await (tableName === 'company_articles' ? supabaseAdmin : sb)
        .from(tableName)
        .select('*', { count: 'exact' })
        .order('created_at', { ascending: false })
        .range(offset, offset + parseInt(limit) - 1);

    if (error) return res.status(500).json({ success: false, error: error.message });
    res.json({ success: true, posts: data, total: count, page: parseInt(page) });
};

export const getArticle = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;
    const { id } = req.params;
    const { target_table } = req.query;
    const tableName = getTableName(userId, target_table);

    const sb = tableName === 'company_articles' ? supabaseAdmin :
        createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false } });

    const { data, error } = await sb.from(tableName).select('*').eq('id', id).single();
    if (error || !data) return res.status(404).json({ success: false, error: 'Not found' });
    res.json({ success: true, post: data });
};

export const updateArticle = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;
    const { id } = req.params;
    const { target_table, is_company_blog, notification_settings, title, ...updates } = req.body;
    const tableName = getTableName(userId, target_table);

    // Map frontend 'title' field to database 'topic' column
    if (title) updates.topic = title;

    const sb = tableName === 'company_articles' ? supabaseAdmin :
        createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false } });

    const { data, error } = await sb.from(tableName).update(updates).eq('id', id).select().single();
    if (error) {
        console.error('Update article error:', error);
        return res.status(500).json({ success: false, error: error.message });
    }

    // Send push if publishing
    if (updates.is_published && data) {
        const notif = updates.notification_settings || {};
        const articleUrl = `${process.env.APP_URL || 'https://www.bitlancetechhub.com'}/blogs/${data.slug}`;

        sendPushNotification(
            notif.title || `New Post: ${data.topic || 'Fresh Content'}`,
            notif.body || data.seo_description || 'Check out our latest update!',
            articleUrl,
            notif.image || data.featured_image
        ).catch(e => console.error('OneSignal Push fail:', e));
    }

    res.json({ success: true, post: data });
};

export const deleteArticle = async (req, res) => {
    const userId = req.user.id;
    const token = req.token;
    const { id } = req.params;
    const { target_table } = req.query;
    const tableName = getTableName(userId, target_table);

    const sb = tableName === 'company_articles' ? supabaseAdmin :
        createClient(process.env.SUPABASE_URL, process.env.SUPABASE_KEY, { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false } });

    const { error } = await sb.from(tableName).delete().eq('id', id);
    if (error) return res.status(500).json({ success: false, error: error.message });
    res.json({ success: true, message: 'Deleted' });
};

// Public endpoints (no auth needed)
export const publicListBlogs = async (req, res) => {
    if (!supabaseAdmin) {
        console.error('publicListBlogs: supabaseAdmin is null — SUPABASE_SERVICE_ROLE_KEY is missing from .env');
        return res.status(503).json({ success: false, error: 'Server misconfiguration: admin client not initialised. Check SUPABASE_SERVICE_ROLE_KEY in .env.' });
    }

    const { page = 1, limit = 10, sort = 'created_at', order = 'desc' } = req.query;
    const offset = (parseInt(page) - 1) * parseInt(limit);

    try {
        const { data, error, count } = await supabaseAdmin
            .from('company_articles')
            .select('id, topic, seo_title, seo_description, image_url, featured_image, slug, category, tags, author_name, publish_date, created_at, estimated_read_time, word_count', { count: 'exact' })
            .eq('is_published', true)
            .order(sort, { ascending: order === 'asc' })
            .range(offset, offset + parseInt(limit) - 1);

        if (error) {
            const isConnectivity = error.message?.includes('fetch') || error.message?.includes('ECONNREFUSED') || error.message?.includes('timeout');
            console.error('publicListBlogs Supabase error:', error.message);
            return res.status(isConnectivity ? 503 : 500).json({
                success: false,
                error: isConnectivity
                    ? 'Database temporarily unavailable — Supabase project may be paused. Visit supabase.com/dashboard to restore it.'
                    : error.message
            });
        }

        const totalPages = Math.ceil(count / parseInt(limit));
        res.json({
            success: true, articles: data,
            pagination: { currentPage: parseInt(page), totalPages, hasNextPage: parseInt(page) < totalPages, hasPrevPage: parseInt(page) > 1, total: count }
        });
    } catch (err) {
        console.error('publicListBlogs unexpected error:', err.message);
        res.status(503).json({
            success: false,
            error: 'Database temporarily unavailable — Supabase project may be paused. Visit supabase.com/dashboard to restore it.'
        });
    }
};

export const publicGetBlog = async (req, res) => {
    const { identifier } = req.params;
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(identifier);

    try {
        const query = supabaseAdmin.from('company_articles').select('*').eq('is_published', true);
        const { data, error } = await (isUuid ? query.eq('id', identifier) : query.eq('slug', identifier)).single();
        if (error || !data) return res.status(404).json({ success: false, error: 'Article not found' });
        res.json({ success: true, article: data });
    } catch (err) {
        console.error('publicGetBlog unexpected error:', err.message);
        res.status(503).json({
            success: false,
            error: 'Database temporarily unavailable — Supabase project may be paused. Visit supabase.com/dashboard to restore it.'
        });
    }
};

// ─────────────────────────────────────────────────────────────────────────────
// COMMENTS endpoints
// ─────────────────────────────────────────────────────────────────────────────

// GET /api/public/blogs/:identifier/comments
export const publicGetComments = async (req, res) => {
    const { identifier } = req.params;
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(identifier);

    try {
        // First resolve the article_id if it's a slug
        let articleId = identifier;
        if (!isUuid) {
            const { data: art, error: artErr } = await supabaseAdmin
                .from('company_articles')
                .select('id')
                .eq('slug', identifier)
                .single();
            if (artErr || !art) return res.status(404).json({ success: false, error: 'Article not found' });
            articleId = art.id;
        }

        const { data, error } = await supabaseAdmin
            .from('comments')
            .select('*')
            .eq('article_id', articleId)
            .eq('status', 'approved')
            .order('created_at', { ascending: false });

        if (error) {
            // Ignore if table doesn't exist yet, just return empty array instead of failing
            if (error.code === '42P01') {
                return res.json({ success: true, comments: [] });
            }
            throw error;
        }

        res.json({ success: true, comments: data || [] });
    } catch (err) {
        console.error('publicGetComments error:', err.message);
        res.status(500).json({ success: false, error: 'Failed to fetch comments' });
    }
};

// POST /api/public/blogs/:identifier/comments
export const publicPostComment = async (req, res) => {
    const { identifier } = req.params;
    const { author_name, text } = req.body;
    const isUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(identifier);

    if (!author_name || !text) {
        return res.status(400).json({ success: false, error: 'Author name and text are required' });
    }

    try {
        // First resolve the article_id if it's a slug
        let articleId = identifier;
        if (!isUuid) {
            const { data: art, error: artErr } = await supabaseAdmin
                .from('company_articles')
                .select('id')
                .eq('slug', identifier)
                .single();
            if (artErr || !art) return res.status(404).json({ success: false, error: 'Article not found' });
            articleId = art.id;
        }

        const { data, error } = await supabaseAdmin
            .from('comments')
            .insert({
                article_id: articleId,
                author_name: author_name.substring(0, 100),
                text: text.substring(0, 5000),
                status: 'approved' // auto-approve for now
            })
            .select()
            .single();

        if (error) {
            if (error.code === '42P01') {
                return res.status(400).json({ success: false, error: 'Comments table has not been created in Supabase yet.' });
            }
            throw error;
        }

        res.json({ success: true, comment: data });
    } catch (err) {
        console.error('publicPostComment error:', err.message);
        res.status(500).json({ success: false, error: 'Failed to post comment' });
    }
};

